language:
  python

python:
  - "2.7"
  - "3.3"

addons:
  postgresql: "9.2"

env:
  - DJANGO=1.6
    PSQL=0
    
  - DJANGO=1.6
    PSQL=1
    
  - DJANGO=1.7
    PSQL=0
        
  - DJANGO=1.7
    PSQL=1
    
before_script:
  - psql -c 'create database travisci;' -U postgres

install:
  - pip install django==$DJANGO coverage six psycopg2 --quiet 

script:
  - export DJANGO_SETTINGS_MODULE=settings
  - export PYTHONPATH=..:$PYTHONPATH
  - cd test_project 
  - python manage.py test interval test_app
  - coverage run --source=../interval manage.py test interval test_app

after_success:
  coveralls
