language:
  python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

addons:
  postgresql: "9.3"

env:
  - DJANGO="Django>=1.6.0,<1.7.0"
    PSQL=0
    
  - DJANGO="Django>=1.6.0,<1.7.0"
    PSQL=1
    
  - DJANGO="Django>=1.7.0,<1.8.0"
    PSQL=0
        
  - DJANGO="Django>=1.7.0,<1.8.0"
    PSQL=1

  - DJANGO="Django>=1.8.0,<1.9.0"
    PSQL=0

  - DJANGO="Django>=1.8.0,<1.9.0"
    PSQL=1
    
before_script:
  - psql -c 'create database travisci;' -U postgres

install:
  - pip install $DJANGO coverage six psycopg2 --quiet 

script:
  - export DJANGO_SETTINGS_MODULE=settings
  - export PYTHONPATH=..:$PYTHONPATH
  - cd test_project 
  - python manage.py test interval test_app
  - coverage run --source=../interval manage.py test interval test_app

after_success:
  coveralls

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=1.6.0,<1.7.0" PSQL=0
    - python: "3.5"
      env: DJANGO="Django>=1.6.0,<1.7.0" PSQL=1
    - python: "3.5"
      env: DJANGO="Django>=1.7.0,<1.8.0" PSQL=0
    - python: "3.5"
      env: DJANGO="Django>=1.7.0,<1.8.0" PSQL=1
